AllCops:
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockNesting:
  Max: 5

Metrics/BlockLength:
  Max: 60

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 600

Metrics/ModuleLength:
  Max: 600

Metrics/ParameterLists:
  Max: 8

Metrics/LineLength:
  Max: 110

# Let's allow empty lines, whitespace == good
Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

# TODO:: resolve indentation width issue once issue is resolved
# https://github.com/bbatsov/rubocop/issues/4105
Lint/EndAlignment:
  AlignWith: start_of_line

Style/ElseAlignment:
  Enabled: false

Style/IndentationWidth:
  Width: 4
  Enabled: false
