AllCops:
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockNesting:
  Max: 5

Metrics/BlockLength:
  Max: 60

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 600

Metrics/ModuleLength:
  Max: 600

Metrics/ParameterLists:
  Max: 8

Style/IndentationWidth:
  Width: 4

Metrics/LineLength:
  Max: 110

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

# Couldn't make this work as expected
Lint/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
  Enabled: false
